# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        detail:
            quality: 75
            filters:
                # use and setup the "fixed" filter
                thumbnail: { size: [800, 350], mode: outbound }

        avatar:
            quality: 75
            filters:
                # use and setup the "fixed" filter
                thumbnail: { size: [60, 60], mode: outbound }

        card:
            quality: 75
            filters:
                # use and setup the "fixed" filter
                thumbnail: { size: [380,350], mode: outbound }

        thumbnail:
            quality: 75
            filters:
                # use and setup the "fixed" filter
                thumbnail: { size: [200,100], mode: outbound }
